### ISSUE TITLE
Add templates 

### ISSUE THREAD

**Issue by Ayush0431** [BigProject404/search4letters#4]
adding templates helps to make the repo beautiful😊

**Comment by BigProject404** [comment]
@Ayush0431 What do you mean 'templates'?

**Comment by BigProject404** [comment]
> adding templates helps to make the repo beautiful😊

@Ayush0431  Sorry I haven't really understood what did you mean because my English is not really good.
But I think I have done what you meant. If I have, please close this issue. Otherwise describe it more clearly.
Thank you

**Comment by BigProject404** [comment]
![image](https://user-images.githubusercontent.com/85517026/148215434-7fb20366-43f3-49d9-8bc7-6763fcb724cc.png)
